### ISSUE TITLE
should add more field types and write validate, cast and infer code (+tests)

### ISSUE THREAD

**Issue by OriHoch** [frictionlessdata/tableschema-php#15]
currently field validation and casting is very basic, need to add more field types
also, need to add some more tests for validating and casting

**Comment by pwalsh** [comment]
This is important. Please review either the JavaScript or the Python implementation, list the missing types, and add support. If there is anything unclear, please ping @roll or myself on the chat channel.

**Comment by OriHoch** [comment]
merged, will be available in next release v0.1.6

constraints are not 100% tested, will be handled in #20
