### ISSUE TITLE
[Task] investigate possible schema inconsistency

### ISSUE THREAD

**Issue by OriHoch** [frictionlessdata/tableschema-php#19]
According to the table schema spec, foreignKeys[0].reference.resource should be uri format and is required.

However, according to description of resource, it includes a possibility to have empty string which references to self.

This does not pass schema validation..

For now, I implemented a hack which allows it to pass validation, but need to see what's the proper way to fix

```js
    "foreignKeys": {
     // ...
          "reference": {
            "type": "object",
            "required": [
              "resource",
              "fields"
            ],
            "properties": {
              "resource": {
                "type": "string",
                "format": "uri"
              },
```

**Comment by pwalsh** [comment]
ref. https://github.com/frictionlessdata/specs/pull/478 

Please review that pull request.

**Comment by OriHoch** [comment]
@pwalsh looks good, it will solve this issue

**Comment by OriHoch** [comment]
fixed
