### ISSUE TITLE
Provide a standalone infer function

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-php#33]
# Overview

For now there is only one `infer` mention in readme. And it says:

> You can instantiate a table object without schema, in this case the schema will be inferred automatically based on the data

```php
$table = new Table("tests/fixtures/data.csv");
$table->schema()->fields();  // ["first_name" => StringField, "last_name" => StringField, "order" => IntegerField]
```
It useful (and often used in other languages) to have this functionality ALSO not related to the `Table` class e.g. as:
- `Schema::infer`

**Comment by OriHoch** [comment]
added in 37487503a3b2f257798433f92ce3d9ebf1564f32
