### ISSUE TITLE
Support bareNumber option for integer and number types

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-php#34]
# Overview

See http://specs.frictionlessdata.io/table-schema/#number (also now there is no `format: currency`)

**Comment by OriHoch** [comment]
done and published in [v0.1.7](https://github.com/frictionlessdata/tableschema-php/releases/tag/v0.1.7)

**Comment by OriHoch** [comment]
@roll 
if bareNumber is set and is false - I just return the value as-is as a string, correct?
this is the relevant code - 
https://github.com/frictionlessdata/tableschema-php/blob/master/src/Fields/IntegerField.php#L16

**Comment by roll** [comment]
@OriHoch 
Please take a look - https://github.com/frictionlessdata/tableschema-js/blob/master/src/types/integer.js#L12-L14 

Non default behaviour is if `bareNumber` is set and `bareNumber==false`. But in this case we should remove all non-numeric characters from start and end of the string. Other casting behaviour is the same.

**Comment by OriHoch** [comment]
fixed in #36
