### ISSUE TITLE
Script generation to export datasets to SQL

### ISSUE THREAD

**Issue by ppKrauss** [frictionlessdata/tableschema-php#35]
The [SQL `COPY`](https://www.postgresql.org/docs/current/static/sql-copy.html) is easy to use, but not generates a compatible `CREATE TABLE`... The SQL-table structure can be obtained by some datatype-translations of `$table->schema()` information... So a suggestion is to add, for instance,  `$table->SQLcopy()` and   `$table->SQLcreate()` methods to accomplish the SQL exportation scripts.

**Comment by OriHoch** [comment]
I think that what you describe is done in [tableschema-sql-py](https://github.com/frictionlessdata/tableschema-sql-py)

if not.. please elaborate :+1:

**Comment by ppKrauss** [comment]
Hi @OriHoch, thanks to the clues. 

Hum... I can implement something here, but need help to understand where to add  the methods ([Table.php](https://github.com/frictionlessdata/tableschema-php/blob/master/src/Table.php) seems the natural place)...  And need to know if I can grow later, with [my  ambitions expressed here](https://github.com/okfn/ideas/issues/93).

**Comment by OriHoch** [comment]
I think this would be more suitable in a new repository - e.g. tableschema-sql-php
 also have a look at frictionless data implementation guide - http://specs.frictionlessdata.io/implementation - which we follow here

**Comment by OriHoch** [comment]
closing the issue as I don't see any remaining action items related to this repository here

feel free to re-open
