### ISSUE TITLE
Courtney Miles should be the lead of the repository

### ISSUE THREAD

**Issue by OriHoch** [frictionlessdata/tableschema-php#41]
# Overview

It seems she is actively using the library, and last 2 PRs were opened by her

I'm less involved with this library, so I suggest to make her the lead of the repository (if she agrees..)

@courtney-miles @roll

**Comment by roll** [comment]
Hi @courtney-miles, do you have any interest? cc @lwinfree 

@OriHoch if not feel free to put `roll` instead of you to the LEAD.md files, for now, so you will not be getting these notifications

**Comment by OriHoch** [comment]
I don't mind being lead as long as there isn't anyone else better suited to do it

**Comment by lwinfree** [comment]
@courtney-miles if you are interested, here is more info: the "leads" are volunteers in the Frictionless community. Their role is to merge PRs & help triage issues. Myself & @roll are 2 main points of contact within the main Frictionless team that can help with any questions. The time commitment is minimal, but isn't non-existent :-) Let me know if you have questions or if you are interested in being the lead for this repo! No pressure either way. Thanks!

**Comment by courtney-miles** [comment]
Hi guys,

Thank you for the offer, and I will be happy to become the lead on this repository.

Let me know if there's any specific processes you would like followed.

*(Note that "she" is a "he" -- a common mistake with my name :smile:)*

**Comment by roll** [comment]
Hi @courtney-miles,

it's great news! 

I've updated the LEAD.md. Regarding processes, there are no specific ones. I think @OriHoch will be able to help you on the initial stage if you have some question e.g. regarding the release process.

**Comment by OriHoch** [comment]
great, thanks @courtney-miles I added you to the repository so you should be able to publish releases

when you publish a release in github it automatically publishes it to [packagist](https://packagist.org/packages/frictionlessdata/tableschema)
