### ISSUE TITLE
Drop support for PHP 5?

### ISSUE THREAD

**Issue by courtney-miles** [frictionlessdata/tableschema-php#44]
hi @OriHoch @roll @lwinfree ,

Are we prepared to drop support for PHP 5 yet?

My vote is to drop support for PHP 5 -- any software still running on PHP 5 can still use version 0.1.9.

---
**Background:**

In #38 I initially dropped support for PHP 5 to be able to upgrade to Carbon 2.  However, there was suggestion at the time that ongoing support for PHP 5 was preferred and the PR went stale.

There is now another PR to upgrade Carbon in #43 

If we don't drop support for PHP 5, then this package cannot be used in software that also uses Carbon and uses PHP 7.

There's another irky PHP compatibility issue with #42 where PHP 7.4 now throws `\Error` instead of `\Exception`. The ideal solution would be to catch `\Throwable` but that change would not be compatible with PHP 5.

Cheers
Courtney

**Comment by courtney-miles** [comment]
... I overlooked there is already an open discussion about this from last year in #39 

If I don't hear any objections within the next few days, I will proceed with changes to drop support for PHP 5.

**Comment by courtney-miles** [comment]
... also, the minimum PHP version supported by any version of Carbon 2 is 7.1.8 -- so this would also drop support for 7.0.

**Comment by OriHoch** [comment]
:+1:

**Comment by courtney-miles** [comment]
Support for PHP 5.6 and 7.0 has been removed.
