### ISSUE TITLE
New release is not automatically published to Packagist

### ISSUE THREAD

**Issue by courtney-miles** [frictionlessdata/tableschema-php#46]
Hi @OriHoch ,

I have released version 0.2.0 and the new version is not appearing on Packagist.

Packagist is suggesting that it is not auto-updated.

<img src="https://user-images.githubusercontent.com/2454544/92992739-7944aa80-f530-11ea-94f5-1c952766cfff.png" width="314" height="406">

Are you able to help with the release?

**Comment by OriHoch** [comment]
fixed, also added you as maintainer on packagist
