### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-php#48]
# Overview

Travis CI is "dying" so we're migrating all the Frictionless libraries to Github Actions.

@courtney-miles, I think we can just copy the @DiegoPino's setup from `datapackage-php`. WDYT?

**Comment by courtney-miles** [comment]
I think it's a good idea to consolidate CI strategies :+1: 

Do you want to raise a PR? Otherwise I am happy replicate the setup from datapackage-php (I'm not familiar with it, but I will figure it out.)

**Comment by DiegoPino** [comment]
@courtney-miles I can give it a try during the week. Will let you know. Thanks

**Comment by courtney-miles** [comment]
@OriHoch are you able to verify if GitHub actions are permitted to run for this repository?

I'm attempting to create a Github action and the `actions/checkout@v2` action is failing with "Resource not accessible by integration"

I'm not sure this is an issue with actions being enabled for the repo, and I have found a similarly reported issue at https://github.com/php-actions/composer/issues/70 so I have posted there.

**Comment by OriHoch** [comment]
@courtney-miles you have full permissions

I described the problem in this comment - https://github.com/php-actions/composer/issues/70#issuecomment-1007174441

I suggest in general to not use external actions, it's fairly simple to write a bash script that runs composer, there is no need to depend on an external action for it, this just introduces more possible problems and security risks..

**Comment by courtney-miles** [comment]
Thankyou @OriHoch 

I'm new to this, and still getting a feel for compiling actions, so appreciate the advise :+1:  I'm confident I will get it working nicely without the external action.

**Comment by courtney-miles** [comment]
I have merged an initial Github action which you can see at https://github.com/frictionlessdata/tableschema-php/blob/b4cdbb8a735161593b52499b195658f48e84d806/.github/workflows/ci.yml

It does not include a step for submitting code coverage to coveralls yet.  This is because it's errors for an unreported reason, and I cannot debug locally due to compatibility issues with my local environment.

I have raised #55 about this.

**Comment by courtney-miles** [comment]
Note that in PR #59 the badge in `README.md` was switched from Travis to Github, and as a part of that the action was renamed from "CI" to "Tests" -- otherwise the label on the badge would be just "CI".
