### ISSUE TITLE
Primary Key is not enforced

### ISSUE THREAD

**Issue by courtney-miles** [frictionlessdata/tableschema-php#64]
This package allows a primary key to be set, but does not enforce the behaviour as per the specification:

> A primary key is a field or set of fields that uniquely identifies each row in
the table. Per SQL standards, the fields cannot be null, so their use in the
primary key is equivalent to adding required: true to their
constraints.

The expectation is that if a table contains a row with a duplicate primary key, then an exception should thrown.

Additionally, an exception should also be thrown if a field that is part of the primary key returns null.

**Comment by courtney-miles** [comment]
Hi @OriHoch ,

May I ask you to confirm if it's Ok for me to add logic for enforcing PK constraints? I just want to be sure it's OK to do so and that my understanding of the specification is correct.

I have a raised a PR with the changes that may be reviewed at #65 .

**Comment by OriHoch** [comment]
best to check the Python library for these things as it's the reference implementation

Looks like it enforces this - https://github.com/frictionlessdata/tableschema-py/blob/main/tests/test_table.py#L141

**Comment by courtney-miles** [comment]
> best to check the Python library for these things as it's the reference implementation

Thanks you -- this is good to know :+1: 

> Looks like it enforces this

I agree... however, it does not appear to enforce that any field listed in the primary key should be treated as required (I.e. do not allow null) so I'm uncertain if to maintain that check or not.

I'm not familiar with Python though, so I may be looking in the wrong place.

**Comment by OriHoch** [comment]
I tested it on the Python library, seems like it doesn't enforce this

**Comment by courtney-miles** [comment]
> I tested it on the Python library, seems like it doesn't enforce this

Thank you for checking this @OriHoch

@roll Are you able to confirm if it is appropriate to raise an exception if a field that is part of the primary key has a null value?

I have added logic for this in PR #65  ([src/Table.php#L187-L195](https://github.com/frictionlessdata/tableschema-php/pull/65/files#diff-9e8be6e8d817d328c7f6f45be86aff7f77a40d97c0625f870c1725c66d4e10daR187-R195)) in response to this statement in the specification:

> Per SQL standards, the fields cannot be null, so their use in the
primary key is equivalent to adding required: true to their
constraints.

However, @OriHoch has confirmed that **frictionlessdata/tableschema-py** does not enforce this condition, so I just want to be certain that my change is appropriate.

**Comment by roll** [comment]
Hi @courtney-miles,

The most up-to-date specs implementation in Python is https://framework.frictionlessdata.io/. And it emits an error in this case :+1:

```
# -------
# invalid: tmp/primary/table.csv
# -------

===  =====  =================  =============================================================================================
row  field  code               message
===  =====  =================  =============================================================================================
  3         primary-key-error  Row at position "3" violates the primary key: cells composing the primary keys are all "None"
===  =====  =================  =============================================================================================
```

**Comment by courtney-miles** [comment]
Thank you @roll
